spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 45628852
    url: jdbc:mysql://39.106.63.214:3306/demo?useUnicode=true&characterEncoding=utf8
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
      # JPA配置
        hbm2ddl.auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

