
# mybatis自身配置
mybatis:
  type-aliases-package: com.pjmike.mybatis.model
  mapper-locations: classpath:mapper/*.xml
  # 驼峰命名规范
  configuration:
    map-underscore-to-camel-case: true

# 通用mapper配置
mapper:
  mappers: com.pjmike.mybatis.MyMapper
  not-empty: false
  # 主键自增回写，默认为 MYSQL
  identity: MYSQL
# 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.63.214:3306/demo?useUnicode=true&characterEncoding=utf8
    username: root
    password: 45628852
server:
  port: 8890


